# -*- coding: utf-8 -*-
"""142856_1-2_tei.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jGX9QlULuq7sVeHSlbS1I8AJ5v2dDKan
"""

from bs4 import BeautifulSoup
import re

# Read the HOCR file
with open("/content/combined_hocr_142856_1-2.hocr", "r", encoding="utf-8") as file:
    hocr_content = file.read()

# Parse the HOCR content
soup = BeautifulSoup(hocr_content, "html.parser")

target_ids = ["bbox 298 361 831 439", "bbox 445 466 681 511", "bbox 294 540 828 615"]

# Initialize a variable to store the extracted text
title_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        title_text += div.get_text(strip=True) + "\n"

# Find the div with class "ocr_carea" and title attribute containing "bbox 153 1361 1012 1401"
div_date_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 256 1222 692 1293" in value)

# Extract text from the second div with the specified format (\d+,\s\w+\s\d+)
if div_date_tag:
    date_text = ""
    text = div_date_tag.get_text(strip=True)
    match = re.search(r"\b\d{1,2}\.\s\w+\s\d{4}\b", text)
    if match:
        date_text = match.group(0)
else:
    date_text = ""

# Find the div with class "ocr_carea" and title attribute containing "bbox 129 1395 985 1460"
div_place_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 129 1395 985 1460" in value)

place_text = ""

# Extract text from the found div
if div_place_tag:
    text = div_place_tag.get_text(strip=True)
    # Match both "Leipzig" and "Berlin" using regular expression
    matches = re.findall(r'\b(?:Leipzig|Berlin)\b', text)
    if matches:
        place_text = " und ".join(matches)  # Join the matches with " und " in between

# Find the div with class "ocr_carea" and title attribute containing "bbox 129 1395 985 1460"
div_org_name_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 129 1395 985 1460" in value)

# Extract text from the third div with the specified format for orgName
if div_org_name_tag:
    org_name_text = ""
    text = div_org_name_tag.get_text(strip=True)
    match = re.search(r"\b[A-Z]\.\s[A-Z][,.]?\s[A-Z][a-z]+", text)
    if match:
        org_name_text = match.group(0)
else:
    org_name_text = ""

# Find the div with class "ocr_carea" and p1 attribute containing "bbox 208 150 1424 290"
div_h1_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 208 150 1424 290" in value)

# Extract text from the first div
if div_h1_tag:
    h1_text = div_h1_tag.get_text(strip=True)
else:
    h1_text = ""

# Find the div with class "ocr_carea" and p1 attribute containing "bbox 207 307 1422 408"
div_p1_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 207 307 1422 408" in value)

# Extract text from the first div
if div_p1_tag:
    p1_text = div_p1_tag.get_text(strip=True)
else:
    p1_text = ""
# Find the div with class "ocr_carea" and p1 attribute containing "bbox 205 511 1001 573"
div_h2_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 205 511 1001 573" in value)

# Extract text from the first div
if div_h2_tag:
    h2_text = div_h2_tag.get_text(strip=True)
else:
    h2_text = ""

# Find the div with class "ocr_carea" and p1 attribute containing "bbox 431 593 1422 751"
div_p2_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 431 593 1422 751" in value)

# Extract text from the first div
if div_p2_tag:
    p2_text = div_p2_tag.get_text(strip=True)
else:
    p2_text = ""

# Find the div with class "ocr_carea" and p1 attribute containing "bbox 208 825 1360 887"
div_h3_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 208 825 1360 887" in value)

# Extract text from the first div
if div_h3_tag:
    h3_text = div_h3_tag.get_text(strip=True)
else:
    h3_text = ""

target_ids = ["bbox 207 902 1103 953", "bbox 464 958 1422 1172", "bbox 431 1176 1421 1335","bbox 465 1336 1421 1431","bbox 432 1446 1420 1544","bbox 431 1556 938 1603","bbox 432 1617 1418 1713","bbox 433 1721 1419 1769"]

# Initialize a variable to store the extracted text
l1_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        l1_text += div.get_text(strip=True) + "\n"

#Find the div with class "ocr_carea" and p3 attribute containing "bbox 205 1805 1221 1856"
div_l2_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 205 1805 1221 1856" in value)

# Extract text from the first div
if div_l2_tag:
    l2_text = div_l2_tag.get_text(strip=True)
else:
    l2_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 564 148 1250 232"
div_h4_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 564 148 1250 232" in value)

# Extract text from the first div
if div_h4_tag:
    h4_text = div_h4_tag.get_text(strip=True)
else:
    h4_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 297 275 857 339"
div_h5_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 297 275 857 339" in value)

# Extract text from the first div
if div_h5_tag:
    h5_text = div_h5_tag.get_text(strip=True)
else:
    h5_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 293 357 1514 963"
div_p3_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 293 357 1514 963" in value)

# Extract text from the first div
if div_p3_tag:
    p3_text = div_p3_tag.get_text(strip=True)
else:
    p3_text = ""

div_h6_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 294 1059 1229 1126" in value)

# Extract text from the first div
if div_h6_tag:
    h6_text = div_h6_tag.get_text(strip=True)
else:
    h6_text = ""

div_h7_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 292 1151 629 1208" in value)

# Extract text from the first div
if div_h7_tag:
    h7_text = div_h7_tag.get_text(strip=True)
else:
    h7_text = ""

# Define a list of target IDs
target_ids = ["bbox 283 1225 1506 1782", "bbox 284 1794 1500 2045"]

# Initialize a variable to store the extracted text
p4_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p4_text += div.get_text(strip=True) + "\n"
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 201 157 1419 455"
div_p5_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 201 157 1419 455" in value)

# Extract text from the first div
if div_p5_tag:
    p5_text = div_p5_tag.get_text(strip=True)
else:
    p5_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 198 465 1424 748"
div_p6_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 198 465 1424 748" in value)

# Extract text from the first div
if div_p6_tag:
    p6_text = div_p6_tag.get_text(strip=True)
else:
    p6_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 196 759 1424 1767"
div_p7_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 196 759 1424 1767" in value)

# Extract text from the first div
if div_p7_tag:
    p7_text = div_p7_tag.get_text(strip=True)
else:
    p7_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 206 1778 1427 2107"
div_p8_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 206 1778 1427 2107" in value)

# Extract text from the first div
if div_p8_tag:
    p8_text = div_p8_tag.get_text(strip=True)
else:
    p8_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 293 151 1513 914"
div_p9_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 293 151 1513 914" in value)

# Extract text from the first div
if div_p9_tag:
    p9_text = div_p9_tag.get_text(strip=True)
else:
    p9_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 294 1005 847 1062"
div_h8_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 294 1005 847 1062" in value)

# Extract text from the first div
if div_h8_tag:
    h8_text = div_h8_tag.get_text(strip=True)
else:
    h8_text = ""

# Find the div with class "ocr_carea" and p3 attribute containing "bbox 286 1081 1508 2052"
div_p10_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 286 1081 1508 2052" in value)

# Extract text from the first div
if div_p10_tag:
    p10_text = div_p10_tag.get_text(strip=True)
else:
    p10_text = ""
#page 6
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 207 167 1427 2063"
div_p11_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 207 167 1427 2063" in value)

# Extract text from the first div
if div_p11_tag:
    p11_text = div_p11_tag.get_text(strip=True)
else:
    p11_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 277 161 1500 2059"
div_p12_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 277 161 1500 2059" in value)

# Extract text from the first div
if div_p12_tag:
    p12_text = div_p12_tag.get_text(strip=True)
else:
    p12_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 199 164 1420 2062"
div_p13_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 199 164 1420 2062" in value)

# Extract text from the first div
if div_p13_tag:
    p13_text = div_p13_tag.get_text(strip=True)
else:
    p13_text = ""
#page 7
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 286 156 1507 1049"
div_p14_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 286 156 1507 1049" in value)

# Extract text from the first div
if div_p14_tag:
    p14_text = div_p14_tag.get_text(strip=True)
else:
    p14_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 284 1053 1504 1800"
div_p15_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 284 1053 1504 1800" in value)

# Extract text from the first div
if div_p15_tag:
    p15_text = div_p15_tag.get_text(strip=True)
else:
    p15_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 288 1845 1502 2053"
div_p16_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 288 1845 1502 2053" in value)

# Extract text from the first div
if div_p16_tag:
    p16_text = div_p16_tag.get_text(strip=True)
else:
    p16_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 205 159 1422 765"
div_p17_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 205 159 1422 765" in value)

# Extract text from the first div
if div_p17_tag:
    p17_text = div_p17_tag.get_text(strip=True)
else:
    p17_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 509 892 1105 1060"
div_h9_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 509 892 1105 1060" in value)

# Extract text from the first div
if div_h9_tag:
    h9_text = div_h9_tag.get_text(strip=True)
else:
    h9_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 208 1090 780 1139"
div_h10_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 208 1090 780 1139" in value)

# Extract text from the first div
if div_h10_tag:
    h10_text = div_h10_tag.get_text(strip=True)
else:
    h10_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 204 1173 901 1225"
div_h11_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 204 1173 901 1225" in value)

# Extract text from the first div
if div_h11_tag:
    h11_text = div_h11_tag.get_text(strip=True)
else:
    h11_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 201 1253 1411 1601"
div_l1_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 201 1253 1411 1601" in value)

# Extract text from the first div
if div_l1_tag:
    l1_text = div_l1_tag.get_text(strip=True)
else:
    l1_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 199 1680 1408 1893"
div_l2_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 199 1680 1408 1893" in value)

# Extract text from the first div
if div_l2_tag:
    l2_text = div_l2_tag.get_text(strip=True)
else:
    hl2_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 251 1621 1107 1662"
div_p18_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 251 1621 1107 1662" in value)

# Extract text from the first div
if div_p18_tag:
    p18_text = div_p18_tag.get_text(strip=True)
else:
    p18_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 199 1930 1001 2059"
div_p19_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 199 1930 1001 2059" in value)

# Extract text from the first div
if div_p19_tag:
    p19_text = div_p19_tag.get_text(strip=True)
else:
    p19_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 279 152 445 195"
div_h12_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 279 152 445 195" in value)

# Extract text from the first div
if div_h12_tag:
    h12_text = div_h12_tag.get_text(strip=True)
else:
    h12_text = ""
# Define a list of target IDs
target_ids = ["bbox 276 200 1491 290", "bbox 327 302 1187 340","bbox 278 353 1495 525"]

# Initialize a variable to store the extracted text
p20_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p20_text += div.get_text(strip=True) + "\n"
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 282 602 397 644"
div_h13_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 282 602 397 644" in value)

# Extract text from the first div
if div_h13_tag:
    h13_text = div_h13_tag.get_text(strip=True)
else:
    h13_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 281 649 1497 977"
div_p21_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 281 649 1497 977" in value)

# Extract text from the first div
if div_p21_tag:
    p21_text = div_p21_tag.get_text(strip=True)
else:
    p21_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 286 1050 435 1094"
div_h14_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 286 1050 435 1094" in value)

# Extract text from the first div
if div_h14_tag:
    h14_text = div_h14_tag.get_text(strip=True)
else:
    h14_text = ""
# Define a list of target IDs
target_ids = ["bbox 284 1099 1498 1355", "bbox 287 1353 1498 1431"]

# Initialize a variable to store the extracted text
p22_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p22_text += div.get_text(strip=True) + "\n"
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 288 1507 404 1550"
div_h15_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 288 1507 404 1550" in value)

# Extract text from the first div
if div_h15_tag:
    h15_text = div_h15_tag.get_text(strip=True)
else:
    h15_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 286 1554 1502 2060"
div_p23_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 286 1554 1502 2060" in value)

# Extract text from the first div
if div_p23_tag:
    p23_text = div_p23_tag.get_text(strip=True)
else:
    p23_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 195 146 1411 595"
div_l3_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 195 146 1411 595" in value)

# Extract text from the first div
if div_l3_tag:
    l3_text = div_l3_tag.get_text(strip=True)
else:
    l3_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 200 650 1414 922"
div_l4_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 200 650 1414 922" in value)

# Extract text from the first div
if div_l4_tag:
    l4_text = div_l4_tag.get_text(strip=True)
else:
    l4_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 253 908 1414 982"
div_l5_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 253 908 1414 982" in value)

# Extract text from the first div
if div_l5_tag:
    l5_text = div_l5_tag.get_text(strip=True)
else:
    l5_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 202 995 1415 1085"
div_l6_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and " bbox 202 995 1415 1085" in value)

# Extract text from the first div
if div_l6_tag:
    l6_text = div_l6_tag.get_text(strip=True)
else:
    l6_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 204 1078 1413 1169"
div_l7_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 204 1078 1413 1169" in value)

# Extract text from the first div
if div_l7_tag:
    l7_text = div_l7_tag.get_text(strip=True)
else:
    l7_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 205 1226 1421 1783"
div_l8_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 205 1226 1421 1783" in value)

# Extract text from the first div
if div_l8_tag:
    l8_text = div_l8_tag.get_text(strip=True)
else:
    l8_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 212 1833 338 1874"
div_l9_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 212 1833 338 1874" in value)

# Extract text from the first div
if div_l9_tag:
    l9_text = div_l9_tag.get_text(strip=True)
else:
    l9_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 209 1869 1423 1963"
div_l10_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 209 1869 1423 1963" in value)

# Extract text from the first div
if div_l10_tag:
    l10_text = div_l10_tag.get_text(strip=True)
else:
    l10_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 261 1970 1421 2044"
div_l11_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 261 1970 1421 2044" in value)

# Extract text from the first div
if div_l11_tag:
    l11_text = div_l11_tag.get_text(strip=True)
else:
    l11_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 281 136 1497 307"
div_l12_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 281 136 1497 307" in value)

# Extract text from the first div
if div_l12_tag:
    l12_text = div_l12_tag.get_text(strip=True)
else:
    l12_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 277 366 1492 503"
div_l13_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 277 366 1492 503" in value)

# Extract text from the first div
if div_l13_tag:
    l13_text = div_l13_tag.get_text(strip=True)
else:
    l13_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 280 514 1494 682"
div_l14_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 280 514 1494 682" in value)

# Extract text from the first div
if div_l14_tag:
    l14_text = div_l14_tag.get_text(strip=True)
else:
    l14_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 276 739 1492 1128"
div_l15_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 276 739 1492 1128" in value)

# Extract text from the first div
if div_l15_tag:
    l15_text = div_l15_tag.get_text(strip=True)
else:
    l15_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 273 1145 1489 1380"
div_l16_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 273 1145 1489 1380" in value)

# Extract text from the first div
if div_l16_tag:
    l16_text = div_l16_tag.get_text(strip=True)
else:
    l16_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 265 1442 1486 2042"
div_l17_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 265 1442 1486 2042" in value)

# Extract text from the first div
if div_l17_tag:
    l17_text = div_l17_tag.get_text(strip=True)
else:
    l17_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 204 141 382 184"
div_h16_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 204 141 382 184" in value)

# Extract text from the first div
if div_h16_tag:
    h16_text = div_h16_tag.get_text(strip=True)
else:
    h16_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 201 191 1415 319"
div_p24_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 201 191 1415 319" in value)

# Extract text from the first div
if div_p24_tag:
    p24_text = div_p24_tag.get_text(strip=True)
else:
    p24_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 203 333 1414 431"
div_p25_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 203 333 1414 431" in value)

# Extract text from the first div
if div_p25_tag:
    p25_text = div_p25_tag.get_text(strip=True)
else:
    p25_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 203 503 325 546"
div_h17_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 203 503 325 546" in value)

# Extract text from the first div
if div_h17_tag:
    h17_text = div_h17_tag.get_text(strip=True)
else:
    h17_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 200 555 1415 642"
div_p26_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 200 555 1415 642" in value)

# Extract text from the first div
if div_p26_tag:
    p26_text = div_p26_tag.get_text(strip=True)
else:
    p26_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 251 655 1412 721"
div_p27_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 251 655 1412 721" in value)

# Extract text from the first div
if div_p27_tag:
    p27_text = div_p27_tag.get_text(strip=True)
else:
    p27_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 200 735 1412 822"
div_p28_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 200 735 1412 822" in value)

# Extract text from the first div
if div_p28_tag:
    p28_text = div_p28_tag.get_text(strip=True)
else:
    p28_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 199 889 1410 1117"
div_p29_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 199 889 1410 1117" in value)

# Extract text from the first div
if div_p29_tag:
    p29_text = div_p29_tag.get_text(strip=True)
else:
    p29_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 198 1130 1409 1225"
div_p30_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 198 1130 1409 1225" in value)

# Extract text from the first div
if div_p30_tag:
    p30_text = div_p30_tag.get_text(strip=True)
else:
    p30_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 197 1289 579 1333"
div_h18_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 197 1289 579 1333" in value)

# Extract text from the first div
if div_h18_tag:
    h18_text = div_h18_tag.get_text(strip=True)
else:
    h18_text = ""
# Define a list of target IDs
target_ids = ["bbox 195 1339 1408 1469", "bbox 242 1481 1104 1551","bbox 194 1560 1405 1658","bbox 193 1653 1405 1740","bbox 191 1809 1402 1907","bbox 241 1918 1401 1984","bbox 191 1998 765 2045"]

# Initialize a variable to store the extracted text
p31_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p31_text += div.get_text(strip=True) + "\n"

# Find the div with class "ocr_carea" and p3 attribute containing "bbox 297 146 1506 318"
div_p32_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 297 146 1506 318" in value)

# Extract text from the first div
if div_p32_tag:
    p32_text = div_p32_tag.get_text(strip=True)
else:
    p32_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 301 330 1507 615"
div_p33_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 301 330 1507 615" in value)

# Extract text from the first div
if div_p33_tag:
    p33_text = div_p33_tag.get_text(strip=True)
else:
    p33_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 299 665 1508 916"
div_p34_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 299 665 1508 916" in value)

# Extract text from the first div
if div_p34_tag:
    p34_text = div_p34_tag.get_text(strip=True)
else:
    p34_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 351 927 1510 997"
div_p35_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 351 927 1510 997" in value)

# Extract text from the first div
if div_p35_tag:
    p35_text = div_p35_tag.get_text(strip=True)
else:
    p35_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 301 1009 1511 1142"
div_p36_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 301 1009 1511 1142" in value)

# Extract text from the first div
if div_p36_tag:
    p36_text = div_p36_tag.get_text(strip=True)
else:
    p36_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 301 1176 1512 1348"
div_p37_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 301 1176 1512 1348" in value)

# Extract text from the first div
if div_p37_tag:
    p37_text = div_p37_tag.get_text(strip=True)
else:
    p37_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 352 1360 1511 1428"
div_p38_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 352 1360 1511 1428" in value)

# Extract text from the first div
if div_p38_tag:
    p38_text = div_p38_tag.get_text(strip=True)
else:
    p38_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 302 1439 1512 1571"
div_p39_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 302 1439 1512 1571" in value)

# Extract text from the first div
if div_p39_tag:
    p39_text = div_p39_tag.get_text(strip=True)
else:
    p39_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 301 1629 864 1747"
div_p40_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 301 1629 864 1747" in value)

# Extract text from the first div
if div_p40_tag:
    p40_text = div_p40_tag.get_text(strip=True)
else:
    p40_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 302 1733 1514 1855"
div_p41_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 302 1733 1514 1855" in value)

# Extract text from the first div
if div_p41_tag:
    p41_text = div_p41_tag.get_text(strip=True)
else:
    p41_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 198 1130 1409 1225"
div_p42_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 198 1130 1409 1225" in value)

# Extract text from the first div
if div_p42_tag:
    p42_text = div_p42_tag.get_text(strip=True)
else:
    p42_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 355 1873 1311 1920"
div_p43_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 355 1873 1311 1920" in value)

# Extract text from the first div
if div_p43_tag:
    p43_text = div_p43_tag.get_text(strip=True)
else:
    p43_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 307 1936 1513 2035"
div_p44_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 307 1936 1513 2035" in value)

# Extract text from the first div
if div_p44_tag:
    p44_text = div_p44_tag.get_text(strip=True)
else:
    p44_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 211 157 1333 328"
div_p45_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 211 157 1333 328" in value)

# Extract text from the first div
if div_p45_tag:
    p45_text = div_p45_tag.get_text(strip=True)
else:
    p45_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 213 341 1424 437"
div_p46_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 213 341 1424 437" in value)

# Extract text from the first div
if div_p46_tag:
    p46_text = div_p46_tag.get_text(strip=True)
else:
    p46_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 213 487 571 606"
div_h19_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 213 487 571 606" in value)

# Extract text from the first div
if div_h19_tag:
    h19_text = div_h19_tag.get_text(strip=True)
else:
    h19_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 213 620 1426 903"
div_p47_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 213 620 1426 903" in value)

# Extract text from the first div
if div_p47_tag:
    p47_text = div_p47_tag.get_text(strip=True)
else:
    p47_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 214 913 1429 1426"
div_p48_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 214 913 1429 1426" in value)

# Extract text from the first div
if div_p48_tag:
    p48_text = div_p48_tag.get_text(strip=True)
else:
    p48_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 216 1473 1431 2049"
div_p49_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 216 1473 1431 2049" in value)

# Extract text from the first div
if div_p49_tag:
    p49_text = div_p49_tag.get_text(strip=True)
else:
    p49_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 292 152 1508 431"
div_p50_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 292 152 1508 431" in value)

# Extract text from the first div
if div_p50_tag:
    p50_text = div_p50_tag.get_text(strip=True)
else:
    p50_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 285 482 1504 997"
div_p51_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 285 482 1504 997" in value)

# Extract text from the first div
if div_p51_tag:
    p51_text = div_p51_tag.get_text(strip=True)
else:
    p51_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 331 1021 1500 1278"
div_p52_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 331 1021 1500 1278" in value)

# Extract text from the first div
if div_p52_tag:
    p52_text = div_p52_tag.get_text(strip=True)
else:
    p52_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 275 1289 1493 1805"
div_p53_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 275 1289 1493 1805" in value)

# Extract text from the first div
if div_p53_tag:
    p53_text = div_p53_tag.get_text(strip=True)
else:
    p53_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 274 1843 500 1892"
div_h20_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 274 1843 500 1892" in value)

# Extract text from the first div
if div_h20_tag:
    h20_text = div_h20_tag.get_text(strip=True)
else:
    h20_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 271 1898 1485 2046"
div_p54_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 271 1898 1485 2046" in value)

# Extract text from the first div
if div_p54_tag:
    p54_text = div_p54_tag.get_text(strip=True)
else:
    p54_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 204 156 1421 532"
div_p55_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 204 156 1421 532" in value)

# Extract text from the first div
if div_p55_tag:
    p55_text = div_p55_tag.get_text(strip=True)
else:
    p55_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 205 549 1421 923"
div_p56_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 205 549 1421 923" in value)

# Extract text from the first div
if div_p56_tag:
    p56_text = div_p56_tag.get_text(strip=True)
else:
    p56_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 205 967 439 1014"
div_h21_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 205 967 439 1014" in value)

# Extract text from the first div
if div_h21_tag:
    h21_text = div_h21_tag.get_text(strip=True)
else:
    h21_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 203 1021 1418 1301"
div_p57_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 203 1021 1418 1301" in value)

# Extract text from the first div
if div_p57_tag:
    p57_text = div_p57_tag.get_text(strip=True)
else:
    p57_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 203 1321 1421 1700"
div_p58_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 203 1321 1421 1700" in value)

# Extract text from the first div
if div_p58_tag:
    p58_text = div_p58_tag.get_text(strip=True)
else:
    p58_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 205 1738 1338 1796"
div_h22_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 205 1738 1338 1796" in value)

# Extract text from the first div
if div_h22_tag:
    h22_text = div_h22_tag.get_text(strip=True)
else:
    h22_text = ""
# Define a list of target IDs
target_ids = ["bbox 202 1795 1415 1891", "bbox 252 1899 1052 1947","bbox 203 1952 1413 2048"]

# Initialize a variable to store the extracted text
p59_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p59_text += div.get_text(strip=True) + "\n"
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 288 157 855 204"
div_h23_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 288 157 855 204" in value)

# Extract text from the first div
if div_h23_tag:
    h23_text = div_h23_tag.get_text(strip=True)
else:
    h23_text = ""
# Define a list of target IDs
target_ids = ["bbox 286 220 1501 639", "bbox 334 677 1500 885","bbox 283 907 1499 1276"]

# Initialize a variable to store the extracted text
p60_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p60_text += div.get_text(strip=True) + "\n"
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 284 1377 515 1423"
div_h24_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 284 1377 515 1423" in value)

# Extract text from the first div
if div_h24_tag:
    h24_text = div_h24_tag.get_text(strip=True)
else:
    h24_text = ""
# Define a list of target IDs
target_ids = ["bbox 283 1438 1497 1578", "bbox 332 1616 1497 1767","bbox 279 1771 1496 2048"]

# Initialize a variable to store the extracted text
p61_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p61_text += div.get_text(strip=True) + "\n"
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 200 163 621 211"
div_h25_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 200 163 621 211" in value)

# Extract text from the fibbox rst div
if div_h25_tag:
    h25_text = div_h25_tag.get_text(strip=True)
else:
    h25_text = ""
# Define a list of target IDs
target_ids = ["bbox 199 224 1413 366", "bbox 249 408 1411 496","bbox 199 534 1413 721"]

# Initialize a variable to store the extracted text
p62_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p62_text += div.get_text(strip=True) + "\n"
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 200 802 1339 852"
div_h26_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 200 802 1339 852" in value)

# Extract text from the first div
if div_h26_tag:
    h26_text = div_h26_tag.get_text(strip=True)
else:
    h26_text = ""
# Define a list of target IDs
target_ids = ["bbox 200 867 1413 1878", "bbox 254 1908 1414 2080"]

# Initialize a variable to store the extracted text
p63_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p63_text += div.get_text(strip=True) + "\n"
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 287 160 1510 1275"
div_p64_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 287 160 1510 1275" in value)

# Extract text from the fibbox rst div
if div_p64_tag:
    p64_text = div_p64_tag.get_text(strip=True)
else:
    p64_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 287 1316 1502 1601"
div_h27_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 287 1316 1502 1601" in value)

# Extract text from the first div
if div_h27_tag:
    h27_text = div_h27_tag.get_text(strip=True)
else:
    h27_text = ""
# Define a list of target IDs
target_ids = ["bbox 337 1621 1204 1667", "bbox 288 1682 1499 1824","bbox 284 1868 1497 1965","bbox 288 1969 1497 2065"]

# Initialize a variable to store the extracted text
p65_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p65_text += div.get_text(strip=True) + "\n"
# Define a list of target IDs
target_ids = ["bbox 207 163 1424 400", "bbox 249 420 1423 516"]

# Initialize a variable to store the extracted text
p66_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p66_text += div.get_text(strip=True) + "\n"
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 205 524 1422 813"
div_p67_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 205 524 1422 813" in value)

# Extract text from the fibbox rst div
if div_p67_tag:
    p67_text = div_p67_tag.get_text(strip=True)
else:
    p67_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 204 849 1421 1079"
div_p68_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 204 849 1421 1079" in value)

# Extract text from the fibbox rst div
if div_p68_tag:
    p68_text = div_p68_tag.get_text(strip=True)
else:
    p68_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 204 1083 1419 1200"
div_p69_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 204 1083 1419 1200" in value)

# Extract text from the fibbox rst div
if div_p69_tag:
    p69_text = div_p69_tag.get_text(strip=True)
else:
    p69_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 202 1209 1418 1398"
div_p70_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 202 1209 1418 1398" in value)

# Extract text from the fibbox rst div
if div_p70_tag:
    p70_text = div_p70_tag.get_text(strip=True)
else:
    p70_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 202 1494 754 1545"
div_h28_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 202 1494 754 1545" in value)

# Extract text from the first div
if div_h28_tag:
    h28_text = div_h28_tag.get_text(strip=True)
else:
    h28_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 200 1570 998 1622"
div_h29_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 200 1570 998 1622" in value)

# Extract text from the first div
if div_h29_tag:
    h29_text = div_h29_tag.get_text(strip=True)
else:
    h29_text = ""
# Define a list of target IDs
target_ids = ["bbox 200 1634 1165 1779", "bbox 201 1788 1202 1844"]

# Initialize a variable to store the extracted text
p71_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p71_text += div.get_text(strip=True) + "\n"
# Define a list of target IDs
target_ids = ["bbox 235 161 1551 219", "bbox 305 615 993 666","bbox 1318 401 1530 525","bbox 261 695 1523 790"]

# Initialize a variable to store the extracted text
l18_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        l18_text += div.get_text(strip=True) + "\n"
# Define a list of target IDs
target_ids = ["bbox 1516 639 1558 722", "bbox 270 822 1080 1168","bbox 1130 965 1282 1005","bbox 272 1202 1079 1336"]

# Initialize a variable to store the extracted text
l19_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        l19_text += div.get_text(strip=True) + "\n"
# Define a list of target IDs
target_ids = ["bbox 1130 1242 1282 1283", "bbox 273 1373 1053 1505","bbox 1131 1410 1281 1451","bbox 271 1539 1079 1629"]

# Initialize a variable to store the extracted text
l20_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        l20_text += div.get_text(strip=True) + "\n"
# Define a list of target IDs
target_ids = ["bbox 1130 1553 1281 1593", "bbox 273 1665 1079 1757","bbox 1130 1678 1281 1718","bbox 1318 1216 1528 1341"]

# Initialize a variable to store the extracted text
l21_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        l21_text += div.get_text(strip=True) + "\n"
# Define a list of target IDs
target_ids = ["bbox 272 1788 1078 1919", "bbox 1114 1826 1280 1867","bbox 1336 1801 1509 1879","bbox 271 1949 1513 2047"]

# Initialize a variable to store the extracted text
l22_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        l22_text += div.get_text(strip=True) + "\n"
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 265 189 1374 238"
div_p72_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 265 189 1374 238" in value)

# Extract text from the fibbox rst div
if div_p72_tag:
    p72_text = div_p72_tag.get_text(strip=True)
else:
    p72_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 262 258 1197 428"
div_h30_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 262 258 1197 428" in value)

# Extract text from the first div
if div_h30_tag:
    h30_text = div_h30_tag.get_text(strip=True)
else:
    h30_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 261 413 1377 743"
div_p73_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 261 413 1377 743" in value)

# Extract text from the fibbox rst div
if div_p73_tag:
    p73_text = div_p73_tag.get_text(strip=True)
else:
    p73_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 262 767 1372 850"
div_p74_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 262 767 1372 850" in value)

# Extract text from the fibbox rst div
if div_p74_tag:
    p74_text = div_p74_tag.get_text(strip=True)
else:
    p74_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 261 860 945 950"
div_h31_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 261 860 945 950" in value)

# Extract text from the first div
if div_h31_tag:
    h31_text = div_h31_tag.get_text(strip=True)
else:
    h31_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 404 945 1373 1204"
div_p75_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 404 945 1373 1204" in value)

# Extract text from the fibbox rst div
if div_p75_tag:
    p75_text = div_p75_tag.get_text(strip=True)
else:
    p75_text = ""
# Define a list of target IDs
target_ids = ["bbox 257 1200 1371 1351", "bbox 257 1336 529 1383"]

# Initialize a variable to store the extracted text
p76_text = ""

# Loop over each target ID
for target_id in target_ids:
    # Find the div element with the specified class and title
    div = soup.find("div", class_="ocr_carea", title=lambda value: value and target_id in value)

    # Extract text from the div if found
    if div:
        p76_text += div.get_text(strip=True) + "\n"

# Find the div with class "ocr_carea" and p3 attribute containing "bbox 258 1394 1372 1474"
div_p77_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 258 1394 1372 1474" in value)

# Extract text from the fibbox rst div
if div_p77_tag:
    p77_text = div_p77_tag.get_text(strip=True)
else:
    p77_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 257 1480 496 1567"
div_h32_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 257 1480 496 1567" in value)

# Extract text from the first div
if div_h32_tag:
    h32_text = div_h32_tag.get_text(strip=True)
else:
    h32_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 251 1564 1370 1921"
div_p78_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 251 1564 1370 1921" in value)

# Extract text from the fibbox rst div
if div_p78_tag:
    p78_text = div_p78_tag.get_text(strip=True)
else:
    p78_text = ""
# Find the div with class "ocr_carea" and p3 attribute containing "bbox 253 1949 1364 2000"
div_p79_tag = soup.find("div", class_="ocr_carea", title=lambda value: value and "bbox 253 1949 1364 2000" in value)

# Extract text from the fibbox rst div
if div_p79_tag:
    p79_text = div_p79_tag.get_text(strip=True)
else:
    p79_text = ""
# Create TEI XML document
tei_xml = f"""
<TEI>
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>{title_text}</title>
        <author>
          <persName></persName>
          <orgName>{org_name_text}</orgName>
        </author>
      </titleStmt>
      <publicationStmt>
        <publPlace>{place_text}</publPlace>
        <date>{date_text}</date>
      </publicationStmt>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <div type="heading">
        <head>{h1_text}</head>
        <p>{p1_text} </p>
        <head>{h2_text}</head>
        <p>{p2_text}</p>
        <head>{h3_text}</head>
        <list type="number">
          <item n="1">{l1_text}</item>
          <item n="2">{l2_text}</item>
      </list>
      </div>
      <div type="heading">
        <head>{h1_text}</head>
        <p>{p1_text} </p>
        <head>{h2_text}</head>
        <p>{p2_text}</p>
        <head>{h3_text}</head>
        <list type="number">
          <item n="1">{l1_text}</item>
          <item n="2">{l2_text}</item>
      </list>
      </div>
      <div type = "heading">
        <head>{h4_text}</head>
        </div>
        <div type="subheading">
        <head>{h5_text}</head>
        <p>{p3_text} </p>
        </div>
        <div type="subheading">
        <head>{h6_text}</head>
        <head>{h7_text}</head>
        <p>{p4_text} </p>
        </div>
        <div>
        <p>{p5_text} </p>
        <p>{p6_text} </p>
        <p>{p7_text} </p>
        <p>{p8_text} </p>
        </div>
        <div>
        <p>{p9_text}</p>
        <head>{h8_text}</head>
        <p>{p10_text}</p>
        </div>
        <div>
        <p>{p11_text}</p>
        </div>
        <div>
        <p>{p12_text}</p>
        </div>
        <div>
        <p>{p13_text}</p>
        </div>
        <div>
        <p>{p14_text}</p>
        <p>{p15_text}</p>
        <p>{p16_text}</p>
        <p>{p17_text}</p>
        </div>
        <div type ="heading">
        <head>{h9_text}</head>
        </div>
        <div type = "subheading">
        <head>{h10_text}</head>
        </div>
        <div>
        <head>{h11_text}</head>
        <list type="number">
        <item n="1">{l1_text} </item>
        <item n ="2">{l2_text}</item>
        </list>
        <p>{p18_text}</p>
        <p>{p19_text}</p>
        </div>
        <div type = "subheading">
        <head>{h12_text}</head>
        <p>{p20_text}</p>
        <head>{h13_text}</head>
        <p>{p21_text}</p>
        <head>{h14_text}</head>
        <p>{p22_text}</p>
        <head>{h15_text}</head>
        <p>{p23_text}</p>
        </div>
        <div>
        <list type="number">
        <item n="1">{l3_text} </item>
        <item n ="2">{l4_text}</item>
        <item n="3">{l5_text} </item>
        <item n ="4">{l6_text}</item>
        <item n="5">{l7_text} </item>
        <item n ="6">{l8_text}</item>
        <item n="7">{l9_text} </item>
        <item n ="8">{l10_text}</item>
        <item n ="9">{l11_text}</item>
        </list>
        </div>
        <div>
        <list type="number">
        <item n="1">{l12_text} </item>
        <item n ="2">{l13_text}</item>
        <item n="3">{l14_text} </item>
        <item n ="4">{l15_text}</item>
        <item n="5">{l16_text} </item>
        <item n ="6">{l17_text}</item>
        </list>
        </div>
        <div>
        <head>{h16_text}</head>
        <p>{p24_text}</p>
        <p>{p25_text}</p>
        <head>{h17_text}</head>
        <p>{p26_text}</p>
        <p>{p27_text}</p>
        <p>{p28_text}</p>
        <p>{p29_text}</p>
        <p>{p30_text}</p>
        <head>{h18_text}</head>
        <p>{p31_text}</p>
        </div>
        <div>
        <p>{p32_text}</p>
        <p>{p33_text}</p>
        <p>{p34_text}</p>
        <p>{p35_text}</p>
        <p>{p36_text}</p>
        <p>{p37_text}</p>
        <p>{p38_text}</p>
        <p>{p39_text}</p>
        <p>{p40_text}</p>
        <p>{p41_text}</p>
        <p>{p42_text}</p>
        <p>{p43_text}</p>
        <p>{p44_text}</p>
        </div>
        <div>
        <p>{p45_text}</p>
        <p>{p46_text}</p>
        <head>{h19_text}</head>
        <p>{p47_text}</p>
        <p>{p48_text}</p>
        <p>{p49_text}</p>
        </div>
        <div>
        <p>{p50_text}</p>
        <p>{p51_text}</p>
        <p>{p52_text}</p>
        <p>{p53_text}</p>
        <head>{h20_text}</head>
        <p>{p54_text}</p>
        </div>
        <div>
        <p>{p55_text}</p>
        <p>{p56_text}</p>
        <head>{h21_text}</head>
        <p>{p57_text}</p>
        <p>{p58_text}</p>
        <head>{h22_text}</head>
        <p>{p59_text}</p>
        </div>
        <div>
        <head>{h23_text}</head>
        <p>{p60_text}</p>
        <head>{h24_text}</head>
        <p>{p61_text}</p>
        </div>
        <div>
        <head>{h25_text}</head>
        <p>{p62_text}</p>
        <head>{h26_text}</head>
        <p>{p63_text}</p>
        </div>
        <div>
        <p>{p64_text}</p>
        <head>{h27_text}</head>
        <p>{p65_text}</p>
        </div>
        <div>
        <p>{p66_text}</p>
        <p>{p67_text}</p>
        <p>{p68_text}</p>
        <p>{p69_text}</p>
        <p>{p70_text}</p>
        <head>{h28_text}</head>
        <head>{h29_text}</head>
        <p>{p71_text}</p>
        </div>
        <div>
        <list type="number">
        <item n="1">{l18_text} </item>
        <item n ="2">{l19_text}</item>
        <item n="3">{l20_text} </item>
        <item n ="4">{l21_text}</item>
        <item n="5">{l22_text} </item>
        </list>
        </div>
        <div>
        <p>{p72_text}</p>
        <head>{h30_text}</head>
        <p>{p73_text}</p>
        <p>{p74_text}</p>
        <head>{h31_text}</head>
        <p>{p75_text}</p>
        <p>{p76_text}</p>
        <p>{p77_text}</p>
        <head>{h32_text}</head>
        <p>{p78_text}</p>
        <p>{p79_text}</p>
        </div>
    </body>
  </text>
</TEI>
"""

# Write TEI XML document to file
with open("output_142856_1-2.tei.xml", "w", encoding="utf-8") as file:
    file.write(tei_xml)